input + print + opération boléen+ None + math + systeme de numération
Microleadoff/content pull request #26
Opened 2024-01-09 09:35 UTC by HrodMarRik

2024-01-09 13:57 UTC, kevinniel requested changes
revoit tout ça !

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0100 - Input AFAIRE/content.md
renommer le dossier principal, virer le " AFAIRE"

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print AFAIRE/content.md
quand tu utilises des listes à puces, utilise des tirets (-) au lieu des plus (+) -> revoir sur tout le fichier.
Pense à virer le AFAIRE du dossier parent
Listes à puces avec des tirets au lieu des +

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes AFAIRE/content.md
Virer le AFAIRE

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes AFAIRE/content.md
> +not
serait probablement mieux sous forme de liste numéroté ici (regarde comment faire en markdown)

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes AFAIRE/content.md
> +Exemples
ça fait chelou le mot exemple sans titre, posé ici, ....

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes AFAIRE/content.md
> +print(x > 3 and x < 10)  # Renvoie True car 5 est entre 3 et 10
redit aussi ici si les 2 comparaisons sont réalisées par python

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes AFAIRE/content.md
> +print(y < 0 or y > 0)  # Renvoie True car y est inférieur à 0
redit aussi ici si les 2 comparaisons sont réalisées par python

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None AFAIRE/content.md
> +None est un littéral spécial en Python qui représente l'absence de valeur ou un vide. C'est un objet unique et un type de données à part entière (NoneType). Voici un guide détaillé sur son utilisatio
un type de donnée (sans s ???)

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None AFAIRE/content.md
> +Définition : None est souvent utilisé pour signifier 'rien' ou 'aucune valeur ici'. Il est similaire à null dans d'autres langages de programmation.
```null```

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None AFAIRE/content.md
> +Utilisez l'opérateur d'identité is pour vérifier si une variable est None. Ne pas utiliser l'opérateur d'égalité ```==```.
d'identité ```is```

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None AFAIRE/content.md
> +### Pourquoi ```is``` et non ```==``` ?
espacement de lignes au dessus et au dessous des titres

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None AFAIRE/content.md
> +
il faudrait ici rajouter un petit laïus pour expliquer la différence entre la valeur et l'identité

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None AFAIRE/content.md
virer le AFAIRE

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0100 - Input/content.md
> +La fonction ```input()``` en Python est un outils essentiel pour interagir avec les utilisateurs en leur permettant de saisir des données pendant l'execution d'un programme.
un outil, pas de s

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0100 - Input/content.md
> +Lorsque l'utilisateur appuie sur Entrée, input() considère cela comme la fin de la saisie et renvoie tout ce qui a été tapé, à l'exception du caractère de fin de ligne (\n).
```input()```

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0100 - Input/content.md
> +Lorsque l'utilisateur appuie sur Entrée, input() considère cela comme la fin de la saisie et renvoie tout ce qui a été tapé, à l'exception du caractère de fin de ligne (\n).
(```\n```)

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +La fonction print() est l'une des fonctions les plus utilisées en Python, car elle permet d'afficher des informations à l'utilisateur. Voici un guide détaillé sur son utilisation et ses caractéristiq
```print()```

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> ++ objects : Ce sont les objets à afficher. print() peut prendre plusieurs objets, séparés par des virgules.
```print()```

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
utilise des tirets (-) au lieu des plus (+) pour les listes à puces

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> ++ objects : Ce sont les objets à afficher. print() peut prendre plusieurs objets, séparés par des virgules.
```objects```

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> ++ sep=' ' : Séparateur à utiliser entre les objets. Par défaut, c'est un espace.
```sep='  '```

2024-01-09 13:57 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> ++ file : Un objet de fichier ou un objet similaire. Par défaut, print() écrit dans la sortie standard (sys.stdout), mais vous pouvez le diriger vers un fichier ou un autre type de flux.
```file```

2024-01-09 20:05 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +Pour or, si le premier opérande est True, Python n'évalue pas le second et renvoie True.
3 tits pour "or", True et True

2024-01-09 20:05 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +1. Utilisez des parenthèses pour rendre vos expressions booléennes plus claires et pour contrôler l'ordre d'évaluation.
attention dans ta liste à mettre 1/2/3 et pas 1/1/1 :D

2024-01-09 20:06 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```None``` est un littéral spécial en Python qui représente l'absence de valeur ou un vide. C'est un objet unique et un type de donnée à part entière (NoneType). Voici un guide détaillé sur son utili
enlève les ":" a la fin. Met un point pour fin de phrase de manière générale lorsque tu as un titre après.

2024-01-09 20:07 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +    ```a = None```
pas d'indentation ?

2024-01-09 20:07 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +Définition : ```None``` est souvent utilisé pour signifier 'rien' ou 'aucune valeur ici'. Il est similaire à ```null``` dans d'autres langages de programmation.
soit tu mets une liste, soit tu mets des sous-titres ici

2024-01-09 20:08 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +
pas de saut de ligne en dessous de la déclaration de code python.
Par contre rajoute un saut de ligne au dessus

2024-01-09 20:08 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```is``` compare les identités des objets, alors que ```==``` compare leurs valeurs. None est un singleton (il n'y a qu'une seule instance de None dans un programme Python), donc il est plus correct
3 tits pour None

2024-01-09 20:10 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```python
+ saut de ligne au dessus, pas de saut de ligne en dessous

2024-01-09 20:10 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```python
+ saut de ligne au dessus, pas de saut de ligne en dessous

2024-01-09 20:10 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```python
+ saut de ligne au dessus, pas de saut de ligne en dessous

2024-01-09 20:11 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```None``` dans les Conditions : ```None``` est considéré comme False dans les conditions. Cependant, il est préférable d'utiliser une vérification explicite avec is None pour la clarté.
3 tits False & None

2024-01-09 20:11 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +Comprendre ```None``` et son utilisation dans Python est crucial pour écrire du code clair et éviter les erreurs subtiles. C'est un outil puissant pour représenter l'absence de valeur et gérer les ca
je pense qu'on peut virer, les gens sont sensé l'avoir compris...

2024-01-09 20:12 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +Les opérations booléennes sont essentielles pour la prise de décision dans les programmes. Comprendre comment les utiliser efficacement est crucial pour tout développeur souhaitant créer des scripts
A virer

2024-01-09 20:12 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +La fonction ```print()``` est simple en surface mais offre une flexibilité considérable pour l'affichage de texte et de données, ce qui en fait un outil indispensable pour tout développeur Python.
A virer

2024-01-09 20:13 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Les systèmes de numération sont une partie fondamentale de l'informatique. Comprendre comment les manipuler en Python est essentiel pour travailler avec des données à bas niveau, effectuer des opérat
A virer

+ virer les sauts de ligne en trop à la fin du fichier

2024-01-09 20:13 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Les opérations mathématiques sont fondamentales dans presque tous les programmes Python.
A virer

2024-01-09 20:15 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Addition (`+`)
3 tits

2024-01-09 20:15 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Soustraction (`-`)
3 tits

2024-01-09 20:15 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Multiplication (`*`)
3 tits

2024-01-09 20:15 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Utilisation : Pour soustraire un nombre d'un autre.
on dit pas "soustraire un nombre à un autre" plutôt ???

2024-01-09 20:15 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Division (`/`)
3 tits

2024-01-09 20:16 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Division Entière (`//`)
3 tits

2024-01-09 20:16 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Modulo (`%`)
3 tits

2024-01-09 20:16 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Puissance (`**`)
3 tits

2024-01-09 20:17 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Utilisation : Utilisez l'opérateur de puissance avec 0.5 ou la fonction sqrt du module math.
3 tits "sqrt" et "math"

2024-01-09 20:17 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +```python
Ajouter un saut de ligne au dessus, virer celui du dessous

2024-01-09 20:17 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Les opérations sont évaluées dans l'ordre suivant : `**`, `*`, `/`, `//`, `%`, `+`, `-`.
3 tits

2024-01-09 20:18 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +```python
Ajouter un saut de ligne au dessus, virer celui du dessous

2024-01-09 20:18 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Lisibilité : Utilisez des espaces autour des opérateurs pour une meilleure lisibilité.
mettre en gras ``` **Lisibilité** ```

2024-01-09 20:18 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Parenthèses : Utilisez-les pour clarifier l'ordre des opérations.
mettre en gras (idem au dessus)

2024-01-09 20:18 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Importation Sélective : Importez uniquement les fonctions nécessaires depuis le module
mettre en gras (idem au dessus)

2024-01-10 08:53 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0100 - Input/content.md
> +```input()``` renvoie toujours une chaîne de caractères (`str`), même si l'utilisateur saisit des nombres. Si vous attendez un type spécifique, vous devez convertir la saisie en conséquence.
ok

2024-01-10 08:53 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0100 - Input/content.md
> +Lorsque l'utilisateur appuie sur Entrée, `input()` considère cela comme la fin de la saisie et renvoie tout ce qui a été tapé, à l'exception du caractère de fin de ligne (`\n`).
ok

2024-01-10 08:53 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +La fonction `print()` est l'une des fonctions les plus utilisées en Python, car elle permet d'afficher des informations à l'utilisateur. Voici un guide détaillé sur son utilisation et ses caractérist
ok

2024-01-10 08:54 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +- `objects` : Ce sont les objets à afficher. ```print()``` peut prendre plusieurs ```objets```, séparés par des virgules.
ok

2024-01-10 09:00 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +- `sep=' '` : Séparateur à utiliser entre les objets. Par défaut, c'est un espace.
ok

2024-01-10 09:00 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +- `end='\n'` : Ce qui est ajouté après tous les objets sont imprimés. Par défaut, c'est un saut de ligne (`\n`), ce qui fait passer à la ligne suivante.
ok

2024-01-10 09:02 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +- `flush` : Si True, le flux de sortie est forcé à être "flushed" (vidé) après l'appel de ```print()```. Utile pour s'assurer que les messages sont écrits immédiatement sans attendre.
ok

2024-01-10 09:02 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +Utilisez l'argument sep pour définir comment les objets sont séparés. Par exemple, print(a, b, c, sep=', ') utilisera une virgule et un espace.
ok

2024-01-10 09:02 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +Utilisez l'argument sep pour définir comment les objets sont séparés. Par exemple, print(a, b, c, sep=', ') utilisera une virgule et un espace.
ok

2024-01-10 09:02 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +L'argument `flush` est souvent utilisé dans des situations où vous avez besoin de vous assurer que la sortie est vue immédiatement, comme dans le cas d'une interface utilisateur interactive ou d'un j
ok

2024-01-10 09:04 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +
ok (-1)

2024-01-10 09:15 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +## Opérateurs Booléens
je pense que c'est ok

2024-01-10 09:18 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +Non égal (!=)** : Vérifie si les valeurs des deux opérandes ne sont pas égales.
oui

2024-01-10 09:21 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +- not
ok

2024-01-10 09:21 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +- and
ok

2024-01-10 09:21 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +- or
ok

2024-01-10 09:32 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +Pour and, si le premier opérande est False, Python n'évalue pas le second et renvoie False.
ok

2024-01-10 09:32 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +Pour or, si le premier opérande est True, Python n'évalue pas le second et renvoie True.
ok

2024-01-10 09:36 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```None``` est un littéral spécial en Python qui représente l'absence de valeur ou un vide. C'est un objet unique et un type de donnée à part entière (NoneType). Voici un guide détaillé sur son utili
ok

2024-01-10 09:37 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +    ```a = None```
modifier sans indentation

2024-01-10 09:39 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +
ok

2024-01-10 09:40 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```is``` compare les identités des objets, alors que ```==``` compare leurs valeurs. None est un singleton (il n'y a qu'une seule instance de None dans un programme Python), donc il est plus correct
ok

2024-01-10 09:40 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```python
ok

2024-01-10 09:40 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```python
ok

2024-01-10 09:40 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```python
ok

2024-01-10 09:41 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```None``` dans les Conditions : ```None``` est considéré comme False dans les conditions. Cependant, il est préférable d'utiliser une vérification explicite avec is None pour la clarté.
ok

2024-01-10 09:42 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +Les opérations booléennes sont essentielles pour la prise de décision dans les programmes. Comprendre comment les utiliser efficacement est crucial pour tout développeur souhaitant créer des scripts
ok

2024-01-10 09:44 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0110 - Print/content.md
> +La fonction ```print()``` est simple en surface mais offre une flexibilité considérable pour l'affichage de texte et de données, ce qui en fait un outil indispensable pour tout développeur Python.
ok

2024-01-10 09:48 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Les systèmes de numération sont une partie fondamentale de l'informatique. Comprendre comment les manipuler en Python est essentiel pour travailler avec des données à bas niveau, effectuer des opérat
ok

2024-01-10 09:49 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Les opérations mathématiques sont fondamentales dans presque tous les programmes Python.
ok

2024-01-10 09:51 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Soustraction (`-`)
ok

2024-01-10 09:51 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Multiplication (`*`)
ok

2024-01-10 09:52 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Utilisation : Pour soustraire un nombre d'un autre.
c'est français mais j'ai changé

2024-01-10 09:52 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Division (`/`)
ok

2024-01-10 09:52 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Division Entière (`//`)
ok

2024-01-10 09:52 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Modulo (`%`)
ok

2024-01-10 09:53 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +### Puissance (`**`)
ok

2024-01-10 09:53 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +```python
ok

2024-01-10 09:54 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Les opérations sont évaluées dans l'ordre suivant : `**`, `*`, `/`, `//`, `%`, `+`, `-`.
oui

2024-01-10 09:54 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +```python
ok

2024-01-10 09:55 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Parenthèses : Utilisez-les pour clarifier l'ordre des opérations.
ok

2024-01-10 09:55 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0150 - Opérations mathématiques/content.md
> +Importation Sélective : Importez uniquement les fonctions nécessaires depuis le module
ok

2024-01-10 10:09 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +## Opérateurs Booléens
Alors non, on s'est pas compris. Exemple : 

### AND (and)

Renvoie ```True``` si les deux opérandes sont vrais.
- **Syntaxe** : ```a and b```
- **Exemple** : (```True and True```) renvoie ```True```.

### OR (or)

Renvoie ```True``` si au moins un des opérandes est vrai.
etc....

2024-01-10 10:10 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0130 - Les opérations booléennes/content.md
> +Court-Circuit
pas de titre sur "cout-circuit" ???

2024-01-10 10:11 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +    def function_with_default_param(param=None):
code indenté pour rien (pas nécessaire)

2024-01-10 10:11 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +```python
code indenté pour rien

2024-01-10 10:12 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +Valeur de Retour par Défaut : Les fonctions en Python retournent ```None``` si aucune valeur n'est explicitement retournée avec return.
3 tits pour "return"

2024-01-10 10:12 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +Vérification Explicite : Toujours utiliser ```is None``` pour vérifier si une variable est ```None```.
met en gras avant les deux points (:)

2024-01-10 10:12 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +Documentation : Lorsque vous utilisez ```None``` dans vos fonctions ou méthodes, documentez clairement ce que cela signifie pour éviter la confusion.
met en gras avant les deux points (:)

2024-01-10 10:13 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0140 - None/content.md
> +Préférez ```None``` à d'autres valeurs : Pour indiquer une valeur 'vide' ou 'par défaut', préférez ```None``` aux autres valeurs comme 0, False, ou une chaîne vide, sauf si vous avez une bonne raison
met en gras avant les deux points (:)

2024-01-10 10:14 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +```python
saut de ligne au dessus

2024-01-10 10:14 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Représentation : Le système que nous utilisons habituellement avec les chiffres de 0 à 9.
Mettre en gras avant les deux points (:)

2024-01-10 10:15 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Aucun préfixe particulier n'est nécessaire.
Ajouter au ébut "Préfixe Python : " pour etre raccord avec la suite du cours.
Mettre en gras avant les deux points (:) (préfixe python)

2024-01-10 10:15 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Représentation : Utilise les chiffres de 0 à 9 et les lettres de A (10) à F (15).
Mettre en gras avant les deux points (:)

2024-01-10 10:15 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Préfixe Python : 0x ou 0X.
Mettre en gras avant les deux points (:)

2024-01-10 10:15 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +### De Binaire :
pas de ":" dans les titres

2024-01-10 10:15 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +### De Octal :
pas de ":" dans les titres

2024-01-10 10:15 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +### De Hexadécimal :
pas de ":" dans les titres

2024-01-10 10:16 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +### Vers Binaire :
pas de ":" dans les titres

2024-01-10 10:16 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +### Vers Octal :
pas de ":" dans les titres

2024-01-10 10:16 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +### Vers Hexadécimal :
pas de ":" dans les titres

2024-01-10 10:16 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Clarté : Utilisez des noms de variables clairs pour indiquer le système de numération.
Mettre en gras avant les deux points (:)

2024-01-10 10:16 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Vérification : Vérifiez toujours le type et la validité des données lors de la conversion entre les systèmes.
Mettre en gras avant les deux points (:)

2024-01-10 10:16 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0160 - Système de numération/content.md
> +Commentaires : Ajoutez des commentaires pour clarifier les conversions et les valeurs particulières.
Mettre en gras avant les deux points (:)

2024-01-10 10:17 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0170 - Caster/content.md
> +  ```python
indent inutile

2024-01-10 10:17 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0170 - Caster/content.md
> +**Utilisation :** Convertit une variable en entier.
ne pas inclure les deux points dans le gras (:)

2024-01-10 10:17 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0170 - Caster/content.md
> +**Syntaxe :**
ne pas inclure les deux points dans le gras (:)

2024-01-10 10:18 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0170 - Caster/content.md
> +
trop de sauts de ligne

2024-01-10 10:18 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0180 - Bitwise operator/content.md
> +- **Utilisation :** Compare chaque bit de ses opérandes. Si les deux bits sont ```1```, le bit de résultat est ```1```.
pas de liste pour une seule ligne

2024-01-10 10:19 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0180 - Bitwise operator/content.md
> +Masquage : Utilisé pour masquer certains bits (par exemple, extraire certains bits spécifiques d'un nombre).
mettre en gras avant les deux points (:)

2024-01-10 10:19 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0180 - Bitwise operator/content.md
> +Paramètres de Configuration : Permet de stocker plusieurs valeurs booléennes dans un seul entier.
mettre en gras avant les deux points (:)

2024-01-10 10:19 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0180 - Bitwise operator/content.md
> +Optimisation : Ces opérateurs peuvent être plus rapides pour certains types de calculs.
mettre en gras avant les deux points (:)

2024-01-10 10:20 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0210 - Scope débutant/content.md
> +**Définition :** Variables définies à l'intérieur d'une fonction.
ne pas mettre les deux points (:) dans le gras

2024-01-10 10:20 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0210 - Scope débutant/content.md
> +**Accès :** Accessibles uniquement dans la fonction où elles sont déclarées.
ne pas mettre les deux points (:) dans le gras

2024-01-10 10:21 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0210 - Scope débutant/content.md
> +  ```python
attention indentation cheloue ici

2024-01-10 10:21 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0210 - Scope débutant/content.md
> +```python
trop d'indentation ici

2024-01-10 10:21 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0210 - Scope débutant/content.md
> +```python
trop d'indentation ici

2024-01-10 10:22 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0210 - Scope débutant/content.md
> +Modification des Variables Globales
ça ne devrait pas être un titre ???

2024-01-10 10:22 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0210 - Scope débutant/content.md
> +  Utilisation de global : Pour modifier une variable globale dans une fonction locale.
en gras avant les deux points (:)

2024-01-10 10:23 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0240 - range()/content.md
> +L'objet "range" utilise le même (peu) de mémoire, quelle que soit la taille de la plage qu'il représente.
début de phrase très chelou. Reformuler

2024-01-10 10:23 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0240 - range()/content.md
> +Boucles ```for``` : Parfait pour exécuter une boucle un nombre spécifique de fois.
mettre en gras avant les deux points (:)

2024-01-10 10:23 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0240 - range()/content.md
> +Génération de Séquences Numériques : Utile pour créer des listes de nombres.
mettre en gras avant les deux points (:)

2024-01-10 10:23 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0240 - range()/content.md
> +Itération par Pas : Utilisez le paramètre ```step``` pour itérer par sauts.
mettre en gras avant les deux points (:)

2024-01-10 10:23 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0240 - range()/content.md
> +Préférez ```range()``` pour les Grandes Séquences : Utilisez ```range()``` au lieu de listes pour économiser de la mémoire, surtout avec de grandes séquences.
mettre en gras avant les deux points (:)

2024-01-10 10:23 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0240 - range()/content.md
> +Compréhension des Itérables : Comprenez que ```range()``` crée un itérable, et non une liste, ce qui a des implications sur la mémoire et la performance.
mettre en gras avant les deux points (:)

2024-01-10 10:24 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0250 - map()/content.md
> +function : Une fonction qui sera appliquée à chaque élément de iterable.
3 tits

2024-01-10 10:24 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0250 - map()/content.md
> +iterable : Un itérable dont les éléments seront traités par function.
3 tits

2024-01-10 10:24 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0250 - map()/content.md
> +resultat est maintenant un objet map contenant [1, 4, 9, 16].
3 tits sur le tableau

2024-01-10 10:24 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0250 - map()/content.md
> +Renvoie un Objet Map : ```map()``` ne retourne pas une liste, mais un objet ```map```, qui est un itérable.
gras avant les deux points (:)

2024-01-10 10:24 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0250 - map()/content.md
> +Efficacité : L'objet ```map``` ne stocke pas tous les résultats en mémoire; il les calcule à la volée, ce qui est plus efficace pour de grands itérables.
gras avant les deux points (:)

2024-01-10 10:25 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0250 - map()/content.md
> +    resultat = map(lambda x: x**2, nombres)
indentation pour rien

2024-01-10 10:25 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0260 - filter()/content.md
> +function : Une fonction qui teste chaque élément de l'itérable. Doit renvoyer ```True``` pour conserver l'élément, ```False``` pour l'exclure.
3 tits

2024-01-10 10:25 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0260 - filter()/content.md
> +iterable : Un itérable (comme une liste ou un tuple) dont les éléments seront testés.
3 tits

2024-01-10 10:26 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0260 - filter()/content.md
> +resultat est maintenant un objet filter contenant [1, 2].
3 tits pour le tableau

2024-01-10 10:26 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0260 - filter()/content.md
> +Nettoyage de Données : Idéal pour éliminer des valeurs indésirables d'un ensemble de données.
gras avant les deux points

2024-01-10 10:26 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0260 - filter()/content.md
> +Sélection Basée sur des Critères : Permet de sélectionner des éléments qui répondent à certaines conditions.
gras avant les deux points

2024-01-10 10:26 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0260 - filter()/content.md
> +```python
Afficher le résultat de l'exécution de la fonction pour simplifier la compréhension

2024-01-10 10:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0270 - reduce()/content.md
> +```python
pas d esaut de ligne en dessous

2024-01-10 10:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0270 - reduce()/content.md
> +Utilisations Courantes
ressemble à un titre ???

2024-01-10 10:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0270 - reduce()/content.md
> +```python
pas d esaut de ligne en dessous

2024-01-10 10:29 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +```python
saut de ligne au dessus

2024-01-10 10:29 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +element : La valeur à vérifier.
3 tits

2024-01-10 10:29 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +sequence : La séquence ou collection dans laquelle vérifier (peut être une liste, un tuple, une chaîne de caractères, etc.).
3 tits

2024-01-10 10:29 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +Cas d'Utilisation
ressemble à un sous titre ???

2024-01-10 10:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +Vérification de Présence : Idéal pour tester si un élément est présent dans une collection.
gras avant les deux points (:)

2024-01-10 10:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +Conditions dans les Boucles et les Instructions Conditionnelles : Souvent utilisé dans les structures```if```, ```while```, etc.
gras avant les deux points (:)

2024-01-10 10:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +Filtrage de Données : Permet de vérifier rapidement l'existence d'une valeur dans des ensembles de données.
gras avant les deux points (:)

2024-01-10 10:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +Séquences : Fonctionne avec des listes, des tuples, des chaînes de caractères, etc.
gras avant les deux points (:)

2024-01-10 10:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +Dictionnaires : in vérifie la présence de clés dans un dictionnaire.
gras avant les deux points (:)

2024-01-10 10:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0280 - in et not in/content.md
> +Ensembles : Utilisé pour vérifier la présence d'éléments dans des ensembles (set).
gras avant les deux points (:)

2024-01-10 10:31 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0310 - Generator AFAIRE/content.md
> +- **Définition :** Un générateur est créé avec une fonction qui utilise l'instruction ```yield```.
pas les deux points dans le gras

2024-01-10 10:31 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0310 - Generator AFAIRE/content.md
> +- **Syntaxe :**
pas les deux points dans le gras

2024-01-10 10:31 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0310 - Generator AFAIRE/content.md
> +  ```python
indentation en trop

2024-01-10 10:31 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0310 - Generator AFAIRE/content.md
> +```python
code trop indenté

2024-01-10 13:47 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0240 - range()/content.md
> +L'objet "range" utilise le même (peu) de mémoire, quelle que soit la taille de la plage qu'il représente.
ça j'ai pas compris

2024-01-10 13:56 UTC, HrodMarRik commented on lang/fr/courses/Développement Générique/Python/courses/0260 - filter()/content.md
> +```python
resultat = filter(lambda x: x > 0, nombres) je dois afficher un resultat pour ça ?

2024-01-10 14:56 UTC, kevinniel requested changes
corrige !

2024-01-10 14:56 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0250 - map()/content.md
> +Combinaison avec d'Autres Itérables
ressemble à un sous-titre ?

2024-01-10 14:56 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0440 - dir() AFAIRE/content.md
Virer le A FAIRE

2024-01-10 14:56 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0450 - Paser de fichier de config AFAIRE/content.md
Virer le A FAIRE
rename le dossier parent : est-ce que c'est pas plutôt "Parser de fichier de config" ???

2024-01-10 15:41 UTC, kevinniel requested changes

2024-01-10 15:41 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0460 - Parser JSON AFAIRE/content.md
Virer le AFAIRE

2024-01-10 15:41 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0450 - Paser de fichier de config AFAIRE/content.md
Virer le AFAIRE

2024-01-10 15:41 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0440 - dir() AFAIRE/content.md
Virer le AFAIRE

2024-01-10 15:41 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0430 - math AFAIRE/content.md
Virer le AFAIRE

2024-01-10 15:41 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0420 - Random AFAIRE/content.md
Virer le AFAIRE

2024-01-10 15:41 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0310 - Generator AFAIRE/content.md
Virer le AFAIRE

2024-01-10 15:41 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0470 - Parser CSV AFAIRE/content.md
Virer le AFAIRE

2024-01-10 15:47 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0440 - dir()/content.md
> +```python
saut de ligne au dessus

2024-01-10 15:48 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0450 - Paser de fichier de config/content.md
> +```csharp
pourquoi csharp ????

2024-01-10 15:48 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0480 - Fichier d'environnement AFAIRE/content.md
a terminer

2024-01-11 08:14 UTC, kevinniel approved these changes
nickel !

2024-01-11 08:14 UTC, merged