PR n°2
Microleadoff/content pull request #27
Opened 2024-01-11 11:51 UTC by HrodMarRik

2024-01-11 12:04 UTC, kevinniel requested changes
peu de changements à faire, mais tu commences à vraiment bien prendre le coup de main.

Pense à virer les AFAIRE à chaque fois, ça nous fera gagner du temps (et on verra quand meme les fichiers que tu as modifié grâce à GIT)

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0560 - pip AFAIRE/content.md
> +- **Définition :** ```pip``` est l'acronyme de "Pip Installs Packages" (Pip Installe des Paquets).
pas les 2 points dans le gras (:)

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0560 - pip AFAIRE/content.md
> +- **Utilisation :** Avec ```pip```, vous pouvez installer des paquets depuis le Python Package Index (```PyPI```) et d'autres dépôts.
pas les 2 points dans le gras (:)

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0570 - Environnements virtuels AFAIRE/content.md
Virer le AFAIRE UNIQUEMENT QUAND LES AUTRES POINTS SERONT TRAITÉS

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0570 - Environnements virtuels AFAIRE/content.md
> +**Création :**
pas les deux points dans le gras (:)

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0580 - package AFAIRE/content.md
Virer le AFAIRE UNIQUEMENT QUAND LES AUTRES POINTS SERONT TRAITÉS

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0580 - package AFAIRE/content.md
> +│ init.py
__init__.py plutôt !

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0700 - Typage python AFAIRE/content.md
Virer le AFAIRE UNIQUEMENT QUAND LES AUTRES POINTS SERONT TRAITÉS

2024-01-11 12:04 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0700 - Typage python AFAIRE/content.md
> +**Objectif :** Améliorer la lisibilité du code, faciliter le débogage et permettre aux outils de vérifier les types de variables, de paramètres de fonction, et de valeurs de retour.
pas les deux points dans le gras (:)

2024-01-12 07:24 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0520 - __name__/content.md
> +- **Définition** : ```__name__``` est une variable intégrée qui obtient sa valeur en fonction de la manière dont le fichier est exécuté.
passe en sous-titre pour définition

2024-01-12 07:25 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0520 - __name__/content.md
> +Exemple de Script avec __name__ :
3 tits

2024-01-12 07:26 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0550 - shebang/content.md
> +- **But :** Indique au système d'exploitation quel interpréteur utiliser pour exécuter le script.
pas les deux points dans le gras (:)

2024-01-12 07:26 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0550 - shebang/content.md
> +- **Shebang Standard pour Python :**
pas les deux points dans le gras (:)
pas de liste !

2024-01-12 07:28 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0580 - package/content.md
> +mon_package/
mettre tout ça dans des 3tits pour que ça s'affiche comme un code. Ne pas spécifier de langage

2024-01-12 07:29 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0770 - decorator AFAIRE/content.md
> +
saut de ligne en trop

2024-01-12 07:29 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0770 - decorator AFAIRE/content.md
> +
saut de ligne en trop

2024-01-12 07:29 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0770 - decorator AFAIRE/content.md
> +
saut de ligne en trop

2024-01-12 07:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0770 - decorator AFAIRE/content.md
> +
saut de ligne en trop

2024-01-12 07:30 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0770 - decorator AFAIRE/content.md
> +
saut de ligne en trop

2024-01-12 09:27 UTC, kevinniel requested changes
2 petites modifs pour valider

2024-01-12 09:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0510 - PEP8/content.md
> +[PEP 8](https://peps.python.org/pep-0008/)
Change le lien, met-le directement en HTML comme suit : 
```<a href="LIEN" title="NOM_DU_LIEN" target="_blank" rel="nofollow">NOM_DU_LIEN</a>```

2024-01-12 09:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0580 - package/content.md
> +
1 saut de ligne en trop

2024-01-12 12:52 UTC, kevinniel requested changes
corrige les noms de fichiers / dossiers

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0760 - pickle AFAIRE/content.md
virer le AFAIRE

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0770 - decorator AFAIRE/content.md
virer le AFAIRE

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0780 - Copie en Python AFAIRE/content.md
virer le AFAIRE

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0780 - Copie en Python AFAIRE/content.md
et modifier le nom du fichier d'ailleurs !

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0790 - tkinter AFAIRE/content.md
virer le AFAIRE

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0850 - shelve AFAIRE/content.md
virer le AFAIRE

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0860 - pygame AFAIRE/content.md
virer le AFAIRE

2024-01-12 12:52 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0860 - pygame AFAIRE/content.md
+ Ajouter le lien vers la doc officielle de pygame pour aller plus loin à la fin du cours

2024-01-12 15:27 UTC, kevinniel requested changes
todo !

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0790 - tkinter/content.md
Ajouter un lien vers la doc officielle de Tkinter à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0850 - shelve/content.md
Ajouter un lien vers la doc officielle de shelve à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0860 - pygame/content.md
Ajouter un lien vers la doc officielle de PyGame à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0960 - setup.py/content.md
Ajouter un lien vers la doc officielle de setuptools à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0970 - unittest AFAIRE/content.md
virer le AFAIRE

+ Ajouter un lien vers la doc officielle de unittest à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/0980 - pytest/content.md
Ajouter un lien vers la doc officielle de Pytest à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/1040 - Subprocess/content.md
Ajouter un lien vers la doc officielle de subprocess à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-12 15:27 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/courses/1050 - argparse/content.md
Ajouter un lien vers la doc officielle de argparse à la fin (avec la balise html directement, en nofollow et en target blank)

2024-01-23 19:45 UTC, Microleadoff requested changes
corriger les quelques détails des cours, et surtout les exos comme on a dit sur discord !

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0530 - __init__/content.md
vu l'emplacement de ce cours, je pense qu'il s'agirait plutôt de parler du fichier __init__ et non pas du constructeur...

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/0530 - __init__/content.md
a vérifier et me redire

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/courses/1080 - Pillow/content.md
> +Pillow est une bibliothèque de traitement d'images en Python, une fourche maintenue de PIL (Python Imaging Library). Elle est utilisée pour ouvrir, manipuler et sauvegarder différents formats de fich
ca veut rien dire

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/exercices/0090 Types de Variables/1.md
manque un tiret dans le titre du fichier

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/exercices/0110 - Print/2.md
> +Vous avez deux variables, nom (avec la valeur "Alice") et âge (avec la valeur 30). Utilisez la fonction ```print()``` pour afficher la phrase "Je m'appelle Alice et j'ai 30 ans."
variables entre 3 tits, et pas d'accents

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/exercices/0110 - Print/3.md
> +- Le programme affiche :
pas de lsite

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/exercices/0110 - Print/3.md
> +  "Roses are red,
entre 3 tits puisque c'est un résultat

2024-01-23 19:45 UTC, Microleadoff commented on lang/fr/courses/Développement Générique/Python/exercices/0110 - Print/4.md
> +Écrivez un programme qui affiche "5 + 10 = 15" en utilisant la fonction `print()` pour afficher les variables a (5), b (10), et leur somme.
donne un code de base peut etre ? avec les variables déjà en place ?

2024-01-30 08:44 UTC, kevinniel requested changes
fait les modifications et répercute les sur tous les exercices !

Essaye de faire ça bien et millimétré parce que je ne ferai probablement pas d'autre review. Si tu n'es pas sûr de toi demande pour le coup !
Enfin, tu mettras tout en production sur microlead, je te montrerais comment faire

2024-01-30 08:44 UTC, kevinniel commented on lang/fr/courses/Développement Générique/Python/exercices/0140 - None/1.md
Intégrer un code de base à compléter

2024-02-06 17:48 UTC, merged